/**
 * 	@file file_resources.h
 *  @author 	FileToC
 *
 *  @brief
 *			Contains information about all file resources.
 *
 *  @version	1.00
 *
 *  @info This file was generated by the ESoPe FileToC.
 *
 ******************************************************************************/

#ifndef _FILE_RESOURCES_H_
#define _FILE_RESOURCES_H_

#include "module_public.h"

#define MODULE_ENABLE_RESOURCE_FILE 1
// #if MODULE_ENABLE_RESOURCE_FILE

//-----------------------------------------------------------------------------------------------------------------------------------------------------------
// Definitions for configuration
//-----------------------------------------------------------------------------------------------------------------------------------------------------------

//-----------------------------------------------------------------------------------------------------------------------------------------------------------
// Configuration
//-----------------------------------------------------------------------------------------------------------------------------------------------------------

//-----------------------------------------------------------------------------------------------------------------------------------------------------------
// Structure
//-----------------------------------------------------------------------------------------------------------------------------------------------------------

/**
 * Contains information about a resource file.
 **/
typedef struct
{
	/// Name of the resource file.
	const char* filename;
	/// Content of the resource file.
	const char* content;
	/// Filesize of the resource file.
	uint32_t filesize;
}file_resource_t;

//-----------------------------------------------------------------------------------------------------------------------------------------------------------
// External variables
//-----------------------------------------------------------------------------------------------------------------------------------------------------------

/**
 * Returns a pointer to the file resource of the file or NULL if there is no resource with the name.
 * @param filename			Name of the file.
 * @return					Pointer to the file resource or NULL.
 **/
const file_resource_t* file_resource_get_by_name(const char* filename);

// #endif // MODULE_ENABLE_RESOURCE_FILE

#endif /* _FILE_RESOURCES_H_ */
